# General settings of the site you can find at /_data/settings.yml

baseurl: "/ChenziWang" # the subpath of your site, e.g. /blog
url: "https://chenzi233.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed
